<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Lost and Found Report - {{ $resort->name }}</title>
    <style>
        body {
            font-family: DejaVu Sans, sans-serif;
            margin: 30px;
            color: #333;
        }

        h3 {
            text-align: center;
            border-bottom: 2px solid #000;
            padding-bottom: 10px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 25px;
        }

        th,
        td {
            border: 1px solid #aaa;
            padding: 8px;
            text-align: left;
            vertical-align: top;
        }

        th {
            background-color: #f2f2f2;
        }

        .footer {
            text-align: center;
            margin-top: 50px;
            font-size: 12px;
            color: #777;
        }
    </style>
</head>

<body>
    <h3>{{ $resort->name }} — Lost and Found Report</h3>

    <p><strong>Date Generated:</strong> {{ now()->format('F d, Y') }}</p>
    <p><strong>Total Records:</strong> {{ $lostItems->count() }}</p>

    <table>
        <thead style="font-size: 12px;">
            <tr>
                <th>#</th>
                <th>Reported By</th>
                <th>Description</th>
                <th>Date</th>
                <th>Location</th>
                <th>Status</th>
                <th>Remarks</th>
                <th>Type</th>
            </tr>
        </thead>
        <tbody style="font-size: 12px;">
            @forelse ($lostItems as $index => $item)
                <tr>
                    <td>{{ $index + 1 }}</td>
                    <td>{{ $item->user?->name ?? 'Guest' }}</td>
                    <td>{{ $item->description ?? 'N/A' }}</td>
                    <td> {{ \Carbon\Carbon::parse($item->date)->format('M d, Y') ?? 'Unknown' }}</td>
                    <td>{{ $item->location ?? 'N/A' }}</td>
                    <td>{{ ucfirst($item->status ?? 'Unspecified') }}</td>
                    <td>{{ $item->remarks ?? 'None' }}</td>
                    <td>{{ ucfirst($item->type ?? 'Unspecified') }}</td>
                </tr>
            @empty
                <tr>
                    <td colspan="8" style="text-align:center;">No lost or found items recorded.</td>
                </tr>
            @endforelse
        </tbody>
    </table>

    <div class="footer">
        Generated by {{ auth()->user()->name ?? 'System' }} | {{ now()->format('M d, Y h:i A') }}
    </div>
</body>

</html>
